[package]
name = "shader"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib"]

[dependencies]
spirv-std = { git = "https://github.com/Rust-GPU/rust-gpu.git", package = "spirv-std" }
glam = { version = "0.32", default-features = false }

[profile.release]
lto = true
opt-level = "z"
